---
apiVersion: v1
kind: Service
metadata:
  namespace: tracing
  name: bar-svc
  labels:
    app: bar-svc
spec:
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: bar-svc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bar-svc
  namespace: tracing
spec:
  selector:
    matchLabels:
      app: bar-svc
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: bar-svc
        version: v1
    spec:
      containers:
        - name: bar-svc
          image: swr.cn-north-4.myhuaweicloud.com/k8s-solution/bar-svc:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: JVM_OPTS
              value: "-Xms256m -Xmx256m"
