---
apiVersion: v1
kind: Service
metadata:
  namespace: tracing
  name: loo-svc
  labels:
    app: loo-svc
spec:
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: loo-svc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loo-svc
  namespace: tracing
spec:
  selector:
    matchLabels:
      app: loo-svc
  replicas: 1
  template:
    metadata:
      labels:
        app: loo-svc
    spec:
      containers:
        - name: loo-svc
          image: swr.cn-north-4.myhuaweicloud.com/k8s-solution/loo-svc:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: JVM_OPTS
              value: "-Xms256m -Xmx256m"
